l_english:
 global_edict_commander_quick_select_settings_event.1.t: "Quick Select Edict Settings"
 global_edict_commander_quick_select_settings_event.1.d: "Instead of going through an event everytime you want to set an edict, you can set an event option to be applied immediately when you click the edict's button.\nIf the option is green, then a quick select option has been enabled for that edict."
 global_edict_commander_quick_select_settings_event.go_back: "Go Back"
 global_edict_commander_quick_select_settings_event.1.advancement: "Advancement Effort"
 global_edict_commander_quick_select_settings_event.1.centralization: "Centralization Effort"
 global_edict_commander_quick_select_settings_event.1.defensive: "Defensive Edict"
 global_edict_commander_quick_select_settings_event.1.dev: "Encourage Development"
 global_edict_commander_quick_select_settings_event.1.manpower: "Increased Enlistment"
 global_edict_commander_quick_select_settings_event.1.trade: "Protect Trade"
 global_edict_commander_quick_select_settings_event.1.missionary_str: "Enforce Religious Unity"
 global_edict_commander_quick_select_settings_event.1.feudal_de_jure: "Feudal De Jure Law"
 global_edict_commander_quick_select_settings_event.1.religion_enforced: "Religion Enforced"
 global_edict_commander_quick_select_settings_event.1.absolutism: "Edict of Absolutism"
 global_edict_commander_quick_select_settings_event.1.feudal_taxes: "Feudal Taxes Edict"
 global_edict_commander_quick_select_settings_event.1.local_separatism: "State Integration Edict"
 global_edict_commander_quick_select_settings_event.1.goods_produced: "Urbanization Edict"
 global_edict_commander_quick_select_settings_event.1.movement: "French Infrastructure Network"
 global_edict_commander_quick_select_settings_event.1.french_trade: "Promote Trade"
 global_edict_commander_quick_select_settings_event.1.china_industrial: "Rapid Industrialization"
 global_edict_commander_quick_select_settings_event.1.governance: "Edict of Governance"

 global_edict_commander_quick_select_settings_events.disable_quick_select: "Disable quick select for this edict."
 global_edict_commander_quick_select_settings_events.disable_quick_select: "We will have to go through the event everytime we select this edict."
 global_edict_commander_quick_select_settings_event.2.t: "Advancement Effort"
 global_edict_commander_quick_select_settings_event.2.d: "TODO"
 global_edict_commander_quick_select_settings_event.3.t: "Centralization Effort"
 global_edict_commander_quick_select_settings_event.3.d: "TODO"
