l_english:
 global_edict_commander_settings_events.1.t: "Global Edict Commander Settings"
 global_edict_commander_settings_events.1.d: "TODO"
 global_edict_commander_settings_events.1.exit: "Exit Settings"
 global_edict_commander_settings_events.1.quick_select_settings: "Quick Select Settings"
 global_edict_commander_settings_events.1.reactive_edicts_settings: "Reactive Edicts Settings"