l_english:
 building_macro_settings_events.1.a: "Configure Build Quantity"
 building_macro_settings_events.1.b: "Configure Manufactory Construction Settings"
 building_macro_settings_events.2.infinite: "Build the Maximum Amount of Buildings Possible"
 building_macro_settings_events.2.build_1: "Build 1 Building at a Time"
 building_macro_settings_events.2.build_5: "Build 5 Buildings at a Time"
 building_macro_settings_events.2.build_10: "Build 10 Buildings at a Time"
 building_macro_settings_events.2.build_25: "Build 25 Buildings at a Time"
 building_macro_settings_events.2.build_50: "Build 50 Buildings at a Time"
 building_macro_settings_events.3.manufactory_settings: "Manufactory Build Settings"
 building_macro_settings_events.3.impressment_offices_settings: "Impressment Offices Build Settings"
 building_macro_settings_events.3.state_house_settings: "State Houses Build Settings"
 building_macro_settings_events.3.soldiers_households_settings: "Soldier's Households Build Settings"
 disable_impressment_office_goods: "Disable trade goods that benefit Impressment Offices"
 disable_impressment_office_goods_tt: "Disables §YFish§!, §YSalt§!, §YNaval Supplies§!, and §YTropical Wood§!."
 disable_state_house_goods: "Disable trade goods that benefit State Houses"
 disable_state_house_goods_tt: "Disables §YPaper§!, §YGlass§!, and §YGems§!."
 disable_soldiers_households_goods: "Disable trade goods that benefit Soldier's Households" 
 disable_soldiers_households_goods_tt: "Disables §YGrain§!, §YFish§!, §YLivestock§!, and §YWine§!."
 enable_impressment_office_goods: "Enable trade goods that benefit Impressment Offices"
 enable_impressment_office_goods_tt: "Enables §YFish§!, §YSalt§!, §YNaval Supplies§!, and §YTropical Wood§!."
 